<?php
// $Id$

/**
 * @file
 * Integration between the bot and google APIs.
 */

/**
 * Implementation of hook_help().
 */
function bot_google_help($path, $args) {
  switch ($path) {
    case 'irc:features':
      return array(t('Search'));
    case 'irc:features#search':
      return t('Search in Google directly from IRC. Syntax: botname: search keywords here');
    case 'irc:features#calculator':
      return t('Convert quantities to different units using the Google calculator. Syntax: botname: convert <amount> <unit> to <unit> or botname: convert <unit> <amount> to <unit>');
  }
}

function bot_google_irc_msg_channel($data, $from_query = FALSE) {
  $to = $from_query ? $data->nick : $data->channel;
  $addressed = bot_name_regexp();

  if (preg_match("/^search (.*)/i", trim($data->message), $matches)) {
    $keywords = $matches[1];
    bot_google_execute_search($keywords);
  }
  if (preg_match("/^$addressed s (.*)/i", $data->message, $matches)) {
    $keywords = $matches[2];
    bot_google_execute_search($to, $keywords);
  }

  $amount = "([0-9]+.?[0-9]+)";
  $unit = "([A-Za-z]{0,3})";
  if (preg_match("/^$addressed convert $amount $unit to $unit$/", $data->message, $matches)) {
    bot_google_execute_calculator($to, $matches[1], $matches[2], $matches[3]);
  }
  if (preg_match("/^$addressed convert $unit $amount to $unit$/", $data->message, $matches)) {
    bot_google_execute_calculator($to, $matches[2], $matches[1], $matches[3]);
  }
}

function bot_google_execute_calculator($to, $amount, $from_unit, $to_unit) {
  $query = drupal_query_string_encode(array(
    'hl' => 'en',
    'q' => "$amount$from_unit=?$to_unit",
  ));
  $url = "http://www.google.com/ig/calculator?$query";
  $result = drupal_http_request($url);
  $data = json_decode($result->data);
  if ($data->error) {
    bot_message($to, t('Query encountered an error: @error', array('@error' => $data->error)));
  }
  else {
    bot_message($to, t('@question is @answer', array('@question' => $data->lhs, '@answer' => $data->rhs)));
  }
}

function bot_google_execute_search($to, $keywords) {
  $search = bot_google_search($keywords);
  if (!empty($search[0]->url)) {
    $output = t("@title => @url - more results: @more", 
      array(
        '@title' => truncate_utf8($search[0]->titleNoFormatting, 40, TRUE, TRUE),
        '@url' => $search[0]->url,
        '@more' => "http://google.com/search?" . drupal_query_string_encode(array('q' => $keywords)),
      )
    );
  }
  else {
    $output = t('Your search - "!keywords" - did not match any documents.', array('!keywords' => $keywords));
  }
  bot_message($to, $output);
}

/**
 * All responses are available via a query.
 */
function bot_google_irc_msg_query($data) {
  bot_google_irc_msg_channel($data, TRUE);
}

/**
 * Search Google using the API.
 */
function bot_google_search($keywords) {
  $query = drupal_query_string_encode(array('v' => '1.0', 'q' => $keywords));
  $google = "http://ajax.googleapis.com/ajax/services/search/web?$query";
  $result = drupal_http_request($google);
  $response = json_decode($result->data);
  return $response->responseData->results;
}
