<?php
// $Id$

/**
 * @file
 * Search in Google directly from IRC.
 */

/**
 * Implementation of hook_help().
 */
function bot_google_help($path, $args) {
  switch ($path) {
    case 'irc:features':
      return array(t('Search'));
    case 'irc:features#search':
      return t('Search in Google directly from IRC. Syntax: botname: search keywords here');
  }
}

function bot_google_irc_msg_channel($data, $from_query = FALSE) {
  $to = $from_query ? $data->nick : $data->channel;
  $addressed = bot_name_regexp();

  if (preg_match("/^search (.*)/i", trim($data->message), $matches)) {
    $keywords = $matches[1];
  }
  elseif (preg_match("/^$addressed s (.*)/i", $data->message, $matches)) {
    $keywords = $matches[2];
  }

  if (isset($keywords)) {
    $search = bot_google_search($keywords);
    $query = drupal_query_string_encode(array('q' => $keywords));
    if (!empty($search[0]->url)) {
      $output = t("@title => @url - more results: @more", 
      array(
        '@title' => truncate_utf8($search[0]->titleNoFormatting, 40, TRUE, TRUE),
        '@url' => $search[0]->url,
        '@more' => "http://google.com/search?$query",
      ));
    }
    else {
      $output = t('Your search - "!keywords" - did not match any documents.', array('!keywords' => $keywords));
    }
    bot_message($to, $output);
  }
}

/**
 * All responses are available via a query.
 */
function bot_google_irc_msg_query($data) {
  bot_google_irc_msg_channel($data, TRUE);
}

/**
 * Search Google using the API.
 */
function bot_google_search($keywords) {
  $query = drupal_query_string_encode(array('v' => '1.0', 'q' => $keywords));
  $google = "http://ajax.googleapis.com/ajax/services/search/web?$query";
  $result = drupal_http_request($google);
  $response = json_decode($result->data);
  return $response->responseData->results;
}
